# Generated by Django 5.2.6 on 2025-09-29 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScrapingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_manodienynas', models.BooleanField(default=True)),
                ('enable_eduka', models.BooleanField(default=True)),
                ('auto_sync_to_google_tasks', models.BooleanField(default=True)),
                ('scraping_frequency_hours', models.PositiveIntegerField(default=6)),
                ('last_scraped_manodienynas', models.DateTimeField(blank=True, null=True)),
                ('last_scraped_eduka', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('manodienynas', 'Manodienynas.lt'), ('eduka', 'Eduka.lt')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_google_tasks', models.BooleanField(default=False)),
                ('google_task_id', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'unique_together': {('user', 'site', 'title', 'due_date')},
            },
        ),
    ]
