# Generated by Django 5.2.6 on 2025-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedhomework',
            options={'ordering': ['due_date', '-scraped_at']},
        ),
        migrations.AddField(
            model_name='scrapedhomework',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapedhomework',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
