# Generated by Django 5.2.6 on 2025-10-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scrapedhomework_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscrapingpreferences',
            name='google_tasks_title_format',
            field=models.CharField(choices=[('title', 'Task Title'), ('subject', 'Subject Name')], default='title', help_text='What to display in Google Tasks header: task title or subject name', max_length=20),
        ),
    ]
