# Generated by Django 5.2.6 on 2025-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_userscrapingpreferences_google_tasks_title_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedhomework',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapedhomework',
            name='synced_to_google_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
