# Generated by Django 5.2.6 on 2025-10-03 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapedhomework_google_calendar_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('manodienynas', 'Manodienynas.lt'), ('eduka', 'Eduka.lt')], max_length=20)),
                ('exam_name', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=200)),
                ('exam_date', models.DateTimeField()),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_google_calendar', models.BooleanField(default=False)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam_date', '-scraped_at'],
                'unique_together': {('user', 'site', 'exam_name', 'exam_date')},
            },
        ),
    ]
