# Generated by Django 5.2.6 on 2025-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_scrapedexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedexam',
            name='google_task_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapedexam',
            name='synced_to_google_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
