# Generated by Django 5.2.6 on 2025-10-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_scrapedexam_google_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedhomework',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapedhomework',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
