# Generated by Django 5.2.6 on 2025-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauth',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
