# Generated by Django 5.2.6 on 2025-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_googleoauth_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='site',
            field=models.CharField(choices=[('blackboard', 'Blackboard'), ('canvas', 'Canvas'), ('moodle', 'Moodle'), ('schoology', 'Schoology'), ('google_classroom', 'Google Classroom'), ('microsoft_teams', 'Microsoft Teams for Education'), ('manodienynas', 'Manodienynas.lt'), ('eduka', 'Eduka.lt')], max_length=50),
        ),
    ]
