# Netlify Configuration for Homework Scraper Frontend
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Directory to publish (Next.js output)
  publish = ".next"
  
  # Base directory for build
  base = "frontend"

[build.environment]
  # Node version (use same as development)
  NODE_VERSION = "20"
  
  # Next.js environment
  NEXT_TELEMETRY_DISABLED = "1"

# Environment variables (set these in Netlify UI for security)
# NEXT_PUBLIC_API_URL = "https://your-backend.onrender.com"

# Redirect rules for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# API proxy to backend (optional - if you want to proxy API calls through Netlify)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend.onrender.com/api/:splat"
  status = 200
  force = false
  headers = {X-From = "Netlify"}

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions (if using Netlify Functions for API routes)
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

# Dev settings for Netlify Dev (local testing)
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  autoLaunch = false
