# Render Blueprint Configuration
# Documentation: https://render.com/docs/blueprint-spec

# Using Supabase for database instead of Render PostgreSQL
# Database credentials are set as environment variables below

services:
  # Django Backend Web Service
  - type: web
    name: homework-scraper-backend
    runtime: python
    plan: free  # Change to 'starter' or higher for production
    region: oregon  # Choose your preferred region
    branch: main
    rootDir: backend
    
    # Build command
    buildCommand: ./build.sh
    
    # Start command (using gunicorn for production)
    startCommand: gunicorn homework_scraper.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    
    # Health check
    healthCheckPath: /api/health
    
    # Environment variables (set sensitive values in Render Dashboard)
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      
      - key: DJANGO_SETTINGS_MODULE
        value: homework_scraper.settings_production
      
      - key: DEBUG
        value: false
      
      - key: SECRET_KEY
        generateValue: true  # Render will auto-generate
      
      - key: ALLOWED_HOSTS
        value: .onrender.com,api.dovydas.space
      
      # Database - Using Supabase PostgreSQL
      # IMPORTANT: Use Session pooler (port 6543) for Django, NOT Transaction pooler (port 5432)
      # Format: postgresql://postgres.[project-ref]:[password]@aws-0-[region].pooler.supabase.com:6543/postgres
      # Get from: Supabase Dashboard → Settings → Database → Connection string (Session pooler)
      - key: DATABASE_URL
        sync: false  # Set manually in Render Dashboard for security
      
      # Supabase Configuration
      - key: SUPABASE_URL
        value: https://kcixuytszyzgvcybxyym.supabase.co
      
      - key: SUPABASE_KEY
        sync: false  # Set manually in Render Dashboard for security
      
      - key: SUPABASE_SERVICE_KEY
        sync: false  # Set manually in Render Dashboard for security
      
      - key: REDIS_URL
        fromService:
          type: redis
          name: homework-scraper-redis
          property: connectionString
      
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: homework-scraper-redis
          property: connectionString
      
      # CORS - Custom domains configured (leave empty to use settings_production.py defaults)
      - key: CORS_ALLOWED_ORIGINS
        sync: false  # Set in Render Dashboard if needed, otherwise uses code defaults
      
      - key: CSRF_TRUSTED_ORIGINS
        sync: false  # Set in Render Dashboard if needed, otherwise uses code defaults
      
      # Frontend URL for OAuth redirects
      - key: FRONTEND_URL
        value: https://nd.dovydas.space
      
      # Google OAuth (set in Render Dashboard)
      - key: GOOGLE_OAUTH2_CLIENT_ID
        sync: false
      
      - key: GOOGLE_OAUTH2_CLIENT_SECRET
        sync: false
      
      - key: GOOGLE_OAUTH_REDIRECT_URI
        value: https://api.dovydas.space/api/auth/google/callback
      
      # Supabase (if used)
      - key: SUPABASE_URL
        sync: false
      
      - key: SUPABASE_KEY
        sync: false
      
      # Encryption key for credentials (MUST be a valid Fernet key)
      # Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
      # Set this manually in Render Dashboard
      - key: ENCRYPTION_KEY
        sync: false
      
      # Playwright (if needed)
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    
    # Disk for SQLite (if not using PostgreSQL)
    # disk:
    #   name: homework-scraper-disk
    #   mountPath: /opt/render/project/src/backend
    #   sizeGB: 1

  # Redis for Celery
  - type: redis
    name: homework-scraper-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    region: oregon
    ipAllowList: []  # Empty = allow all

  # Celery Worker (Background tasks)
  - type: worker
    name: homework-scraper-celery
    runtime: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install psycopg2-binary
      playwright install chromium
    
    startCommand: celery -A homework_scraper worker --loglevel=info --concurrency=2
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      
      - key: DJANGO_SETTINGS_MODULE
        value: homework_scraper.settings_production
      
      # Database - Using Supabase PostgreSQL
      # IMPORTANT: Use Session pooler (port 6543) for Django
      # Get from: Supabase Dashboard → Settings → Database → Connection string (Session pooler)
      - key: DATABASE_URL
        sync: false  # Set manually in Render Dashboard
      
      # Supabase Configuration
      - key: SUPABASE_URL
        value: https://kcixuytszyzgvcybxyym.supabase.co
      
      - key: SUPABASE_KEY
        sync: false
      
      - key: REDIS_URL
        fromService:
          type: redis
          name: homework-scraper-redis
          property: connectionString
      
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: homework-scraper-redis
          property: connectionString
      
      - key: SECRET_KEY
        sync: false
      
      - key: ENCRYPTION_KEY
        sync: false
      
      # Playwright
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright

  # Celery Beat (Scheduled tasks)
  - type: worker
    name: homework-scraper-celery-beat
    runtime: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install psycopg2-binary
    
    startCommand: celery -A homework_scraper beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      
      - key: DJANGO_SETTINGS_MODULE
        value: homework_scraper.settings_production
      
      # Database - Using Supabase PostgreSQL
      # IMPORTANT: Use Session pooler (port 6543) for Django
      # Get from: Supabase Dashboard → Settings → Database → Connection string (Session pooler)
      - key: DATABASE_URL
        sync: false  # Set manually in Render Dashboard
      
      # Supabase Configuration
      - key: SUPABASE_URL
        value: https://kcixuytszyzgvcybxyym.supabase.co
      
      - key: SUPABASE_KEY
        sync: false
      
      - key: REDIS_URL
        fromService:
          type: redis
          name: homework-scraper-redis
          property: connectionString
      
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: homework-scraper-redis
          property: connectionString
      
      - key: SECRET_KEY
        sync: false
